int main() try {

    return 0;
} catch (const std::exception & ex) {
    std:: cout << ex.what();
}
